define pareigos=CLERK;
select ename, job, sal, mgr, deptno from emp where job='&pareigos';

define metinis=sal*12;
select ename, job, sal, mgr, deptno, &metinis "Metinis" from emp where &metinis > 30000;

select RPAD(ENAME,10,' ') || LPAD(JOB,10,' ') as "EMPLOYEE_AND_JOB" from EMP where ename='SMITH' or ename='ALLEN';


select ename,months_between(sysdate,hiredate), to_char(trunc(months_between(sysdate,hiredate)/12,0)) "YEARS OF SERVICE" from EMP where ename='KING';

select * from client order by ename;


SELECT * FROM CLIENT;

SELECT * FROM PROJECT
ORDER BY PROJECT_NAME;


SELECT C_FIRST_NAME, C_LAST_NAME FROM CLIENT
WHERE C_CITY = 'Middlefield' or C_CITY = 'Someplace' or C_CITY = 'Hometown';

SELECT * FROM CLIENT
WHERE C_STATE = 'CA'
ORDER BY C_CITY;

SELECT 'Klientas ' || SUBSTR(C_FIRST_NAME, 1, 1) || '. ' || C_LAST_NAME || ' gyvena ' || C_STREET || ', ' || UPPER(C_CITY) || ', ' || C_STATE FROM CLIENT;

SELECT C_CITY, COUNT(client_id) FROM CLIENT
GROUP BY C_CITY;

SELECT PROJECT_NAME, BUDGET FROM PROJECT
WHERE PROJECT_FINISH_DATE - PROJECT_START_DATE > 155 AND PROJECT_FINISH_DATE > CURRENT_DATE;

SELECT MIN(SAL) AS LOWEST_SAL, MAX(SAL) AS MAX_SAL FROM EMP
WHERE DEPTNO = '30'
GROUP BY JOB
HAVING (MAX(SAL) - MIN(SAL)) > 1000;

SELECT EMP.EMPNO, EMP.ENAME, PROJECT.PROJECT_NAME, PROJECT.PROJECT_START_DATE, PROJECT_FINISH_DATE FROM EMP, PROJECT
WHERE PROJECT.MANAGER_ID = EMP.EMPNO and PROJECT_FINISH_DATE < CURRENT_DATE;

SELECT PROJECT.PROJECT_ID, PROJECT.PROJECT_NAME, EMP.ENAME AS MANAGER, CLIENT.C_LAST_NAME FROM PROJECT, EMP, CLIENT
WHERE PROJECT.MANAGER_ID = EMP.EMPNO and PROJECT.CLIENT_ID = CLIENT.CLIENT_ID;



SELECT * FROM CLIENT;
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM PROJECT;



SELECT EMP.ENAME, SAL AS MANAGER FROM EMP 
JOIN PROJECT
ON PROJECT.MANAGER_ID = EMP.EMPNO;

SELECT EMP.ENAME, SAL AS MANAGER FROM EMP
WHERE EMP.JOB = 'SALESMAN'
JOIN PROJECT
ON PROJECT.MANAGER_ID = EMP.EMPNO;

